// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA1S_yzWTv_eBOERvvnz_ivF-8q9M0KX0',
    appId: '1:706115295900:web:c1024dfde018745598ab59',
    messagingSenderId: '706115295900',
    projectId: 'flutter-coding-challenge-a89c8',
    authDomain: 'flutter-coding-challenge-a89c8.firebaseapp.com',
    storageBucket: 'flutter-coding-challenge-a89c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA6QvuWnBfQ_9KOYK7uQan9a-CeVuJcKg',
    appId: '1:706115295900:android:0b69558cc0d3063c98ab59',
    messagingSenderId: '706115295900',
    projectId: 'flutter-coding-challenge-a89c8',
    storageBucket: 'flutter-coding-challenge-a89c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD66Ee9QjfNkMylGhZtyFNkaGze4FaxE3A',
    appId: '1:706115295900:ios:606c8ece749a333198ab59',
    messagingSenderId: '706115295900',
    projectId: 'flutter-coding-challenge-a89c8',
    storageBucket: 'flutter-coding-challenge-a89c8.appspot.com',
    iosClientId: '706115295900-pq3i6uhq78paijjkmm2hthitsgjua0d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCodingChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD66Ee9QjfNkMylGhZtyFNkaGze4FaxE3A',
    appId: '1:706115295900:ios:812cfb60d560255b98ab59',
    messagingSenderId: '706115295900',
    projectId: 'flutter-coding-challenge-a89c8',
    storageBucket: 'flutter-coding-challenge-a89c8.appspot.com',
    iosClientId: '706115295900-l33cjd5itvmg60t6h9lj3299uegllhkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCodingChallenge.RunnerTests',
  );
}
